# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- develop

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Npm@1
  inputs:
    command: 'install'
    workingDir: 'server'

- task: Npm@1
  inputs:
    command: 'install'
    workingDir: 'server'

- task: Npm@1
  inputs:
    command: 'install'
    workingDir: 'kinder'
- task: NodeTool@0
  inputs:
    versionSpec: '10.16.3'
  displayName: 'Install Node.js'

- script: |
    npm run test
  displayName: 'npm test and build server'
  workingDirectory: 'server'

- script: |
   npm run build
   npm run test
  displayName: 'npm build and test client'
  workingDirectory: 'kinder'
